//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountStatusWeb.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBill
    {
        public int idBill { get; set; }
        public string CODIGO_CLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string TIPO_DE_DOCUMENTO { get; set; }
        public string NUMERO { get; set; }
        public Nullable<System.DateTime> EMISION { get; set; }
        public Nullable<System.DateTime> VENCIMIENTO { get; set; }
        public string OBSERVACION { get; set; }
        public string CODIGO_VENDEDOR { get; set; }
        public Nullable<decimal> BASE { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> NETO { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<decimal> INT_MORATORIOS { get; set; }
        public Nullable<decimal> H_PROFESIONALES { get; set; }
        public Nullable<decimal> TOTAL_A_PAGAR_POR_MOROSIDAD { get; set; }
    }
}
