//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountStatusWeb.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tClient
    {
        public int idClient { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string RIF { get; set; }
        public string NIT { get; set; }
        public Nullable<bool> CONTIBUYENTE { get; set; }
        public Nullable<bool> INACTIVO { get; set; }
        public string RESPONSABLE { get; set; }
        public Nullable<System.DateTime> FECHA_REG { get; set; }
        public Nullable<double> TIPO { get; set; }
        public string DES_TIPO { get; set; }
        public string DIREC1 { get; set; }
        public string DIREC2 { get; set; }
        public string TELEFONOS { get; set; }
        public string FAX { get; set; }
        public Nullable<double> SEGMENTO { get; set; }
        public string SEG_DES { get; set; }
        public Nullable<double> ZONA { get; set; }
        public string ZON_DES { get; set; }
        public string VENDEDOR { get; set; }
        public string VEN_DES { get; set; }
        public string DIR_ENT2 { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<double> CO_INGR { get; set; }
        public string EMAIL { get; set; }
        public string CO_SUCU { get; set; }
        public string CIUDAD { get; set; }
        public Nullable<double> ZIP { get; set; }
        public string PAIS { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<System.DateTime> mailSentAt { get; set; }
    }
}
