//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountStatusWeb.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tReport()
        {
            this.tReportMessage = new HashSet<tReportMessage>();
            this.tReportParameter = new HashSet<tReportParameter>();
        }
    
        public short idReport { get; set; }
        public Nullable<byte> idReportServerConfig { get; set; }
        public Nullable<byte> idSmtp { get; set; }
        public Nullable<byte> idCountry { get; set; }
        public Nullable<byte> idAttachment { get; set; }
        public Nullable<short> idEmailAccountSender { get; set; }
        public Nullable<short> idEmailAccountMonitoring { get; set; }
        public Nullable<byte> idImageConfig { get; set; }
        public Nullable<byte> idLogConfig { get; set; }
        public Nullable<byte> idSignature { get; set; }
        public Nullable<byte> idProcedureLoadData { get; set; }
        public string name { get; set; }
        public string path { get; set; }
        public string subject { get; set; }
        public byte idStatus { get; set; }
        public System.DateTime createdAt { get; set; }
        public short createdBy { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<short> updatedBy { get; set; }
    
        public virtual tAttachment tAttachment { get; set; }
        public virtual tCountry tCountry { get; set; }
        public virtual tEmailAccount tEmailAccount { get; set; }
        public virtual tImageConfig tImageConfig { get; set; }
        public virtual tLogConfig tLogConfig { get; set; }
        public virtual tProcedureLoadData tProcedureLoadData { get; set; }
        public virtual tReportServerConfig tReportServerConfig { get; set; }
        public virtual tSignature tSignature { get; set; }
        public virtual tSmtp tSmtp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReportMessage> tReportMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tReportParameter> tReportParameter { get; set; }
    }
}
